trigger: 
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - /**/*.md
      - /docs/**/*

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: "Release"
  baseUrl: "https://$(webAppName).azurewebsites.net/"

stages:
  - stage: build
    jobs:
      - job: db

      - job: backend
        steps:
          - task: replacetokens@3
            inputs:
              targetFiles: '$(System.DefaultWorkingDirectory)/backend/nuget.config'
              encoding: 'utf-8'
              writeBOM: true
              escapeType: 'json'
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '___'
              tokenSuffix: '___'
              useLegacyPattern: false
              enableTransforms: false
              enableTelemetry: true

          - task: NuGetCommand@2
            inputs:
              command: 'restore'
              restoreSolution: '**/*.sln'
              feedsToUse: 'config'
              nugetConfigPath: '$(System.DefaultWorkingDirectory)/backend/nuget.config'
          
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              workingDirectory: '$(System.DefaultWorkingDirectory)/backend'
              configuration: $(buildConfiguration)
          
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              testSelector: "testAssemblies"
              testAssemblyVer2: |
                **\*test*.dll
                !**\*TestAdapter.dll
                !**\obj\**
              codeCoverageEnabled: true
              platform: 'Any CPU'
              searchFolder: '$(System.DefaultWorkingDirectory)/backend'

          - task: CopyPublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/backend/HFundamentals.Sample/bin/$(buildConfiguration)/net5.0/'
              ArtifactName: 'backend'
              publishLocation: 'Container'

      - job: frontend

  - stage: release
    dependsOn: build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main''))