trigger:
  - develop
  - main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: "Release"

stages:
  - stage: build
    displayName: Build frontend
    jobs:
      - job: frontend
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"
            displayName: "Install Node.js"

          - script: npm install
            displayName: "npm install"
            workingDirectory: "$(System.DefaultWorkingDirectory)/frontend/"

          - script: npm run build
            displayName: "build"
            workingDirectory: "$(System.DefaultWorkingDirectory)/frontend/"

          - script: npm run test
            displayName: "test"
            workingDirectory: "$(System.DefaultWorkingDirectory)/frontend/"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(System.DefaultWorkingDirectory)/frontend/dist/"
              ArtifactName: "frontend"
              publishLocation: "Container"

  - stage: release
    displayName: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - deployment: deploy_frontend_beta
        displayName: Deploy frontend (beta)
        environment: beta_env
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "frontend"
                    downloadPath: "$(System.ArtifactsDirectory)"
                - task: AzureFileCopy@4
                  inputs:
                    SourcePath: "$(System.ArtifactsDirectory)/frontend"
                    azureSubscription: "Visual Studio Enterprise(66617915-b071-43f5-b408-ccfcf9c4ab1e)"
                    Destination: "AzureBlob"
                    storage: "$(betaStorage)"
                    ContainerName: "$web"
